config/routes.rb
JobApplicationApp::Application.routes.draw do
  
  resources :vacant_jobs

  get "sessions/new"

  resources :interviews

  resources :applications

  resources :applicants

  resources :interviewers

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'interviewers#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/application.rb
class Application < ActiveRecord::Base
	belongs_to :applicant
	belongs_to :interviewer
	has_many :interviews
	belongs_to :vacant_job
  	attr_accessible :applicant_id, :application_status, :cv, :linkedin, :military_status, :priority, :vacant_job_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  # GET /applications
  # GET /applications.json
  def index
    @applications = Application.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applications }
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
    @application = Application.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/new
  # GET /applications/new.json
  def new
    @application = Application.new
    puts params.to_json
    @job_id = params[:job_id]
    puts "ffffffffffffffffffffffffffffff"
    puts @job_id
    puts "ffffffffffffffffffffffffffffff"
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @application }
    end
  end

  # GET /applications/1/edit
  def edit
    @application = Application.find(params[:id])
  end

  # POST /applications
  # POST /applications.json
  def create
    #puts params.to_json
    #puts params["name_label"]
    applicant = Applicant.find_by_email(params["email_label"])
    #puts applicant.to_json
    if applicant == nil
      #applicant found add new appliccation to it
      applicant = Applicant.create(:name => params["name_label"], 
        :email => params["email_label"])
    end
    @application = Application.new(:cv =>params[:application][:cv], 
      :linkedin => params[:application][:linkedin], 
      :priority => params[:application][:priority], 
      :military_status => params[:application][:military_status], 
      :vacant_job_id => params[:application][:vacant_job_id], 
      :application_status => "1", 
      :applicant_id => applicant.id )

    respond_to do |format|
      if @application.save
        format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.json { render json: @application, status: :created, location: @application }
      else
        format.html { render action: "new" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /applications/1
  # PUT /applications/1.json
  def update
    @application = Application.find(params[:id])

    respond_to do |format|
      if @application.update_attributes(params[:application])
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application = Application.find(params[:id])
    @application.destroy

    respond_to do |format|
      format.html { redirect_to applications_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <label for="user_name">Name</label><br />
    <input id="user_name" name="name_label" size="30" type="text" />
  </div>

  <div class="field">
    <label for="applicant_email">e-mail</label><br />
    <input id="applicant_email" name="email_label" size="30" type="text" />
  </div>

  <div class="field">
    <%= f.label :cv %><br />
    <%= f.text_field :cv %>
  </div>
  <div class="field">
    <%= f.label :linkedin %><br />
    <%= f.text_field :linkedin %>
  </div>
  <div class="field">
    <%= f.label :priority %><br />
    <%= f.number_field :priority %>
  </div>
  <div class="field">
    <%= f.label :military_status %><br />
    <%= f.number_field :military_status %>
  </div>
  <div class="field">
    <%= f.hidden_field :vacany_id, :value => @job_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<h1>Listing applications</h1>

<table>
  <tr>
    <th>Cv</th>
    <th>Linkedin</th>
    <th>Priority</th>
    <th>Military status</th>
    <th>Application status</th>
    <th>Applicant</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @applications.each do |application| %>
  <tr>
    <td><%= application.cv %></td>
    <td><%= application.linkedin %></td>
    <td><%= application.priority %></td>
    <td><%= application.military_status %></td>
    <td><%= application.application_status %></td>
    <td><%= application.applicant.name %></td>
    <td><%= link_to 'Show', application %></td>
    <td><%= link_to 'Edit', edit_application_path(application) %></td>
    <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cv:</b>
  <%= @application.cv %>
</p>

<p>
  <b>Linkedin:</b>
  <%= @application.linkedin %>
</p>

<p>
  <b>Priority:</b>
  <%= @application.priority %>
</p>

<p>
  <b>Military status:</b>
  <%= @application.military_status %>
</p>

<p>
  <b>Vacany:</b>
  <%= @application.vacant_job_id %>
</p>

<p>
  <b>Application status:</b>
  <%= @application.application_status %>
</p>

<p>
  <b>Applicant:</b>
  <%= @application.applicant_id %>
</p>


<table>
  <tr>
    <th>Score</th>
    <th>Application</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @application.interviews.each do |interview| %>
  <tr>
    <td><%= interview.score %></td>
    <td><%= interview.application_id %></td>
    <td><%= interview.type_id %></td>
    <td><%= link_to 'Show', interview %></td>
    <td><%= link_to 'Edit', edit_interview_path(interview) %></td>
    <td><%= link_to 'Destroy', interview, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>



<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>