config/routes.rb
JobApplicationApp::Application.routes.draw do
  
  resources :vacant_jobs

  get "sessions/new"

  resources :interviews

  resources :applications

  resources :applicants

  resources :interviewers

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'interviewers#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/applicant.rb
class Applicant < ActiveRecord::Base
  attr_accessible :email, :name

  has_many :applications


  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name,	:presence => true,
  					:length => { :maximum => 50 }

  validates :email, :presence => true,
  					:format => { :with => email_regex },
  					:uniqueness => true

end

app/controllers/applicants_controller.rb
class ApplicantsController < ApplicationController
  # GET /applicants
  # GET /applicants.json
  def index
    @applicants = Applicant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @applicants }
    end
  end

  # GET /applicants/1
  # GET /applicants/1.json
  def show
    @applicant = Applicant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @applicant }
    end
  end

  # GET /applicants/new
  # GET /applicants/new.json
  def new
    @applicant = Applicant.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @applicant }
    end
  end

  # GET /applicants/1/edit
  def edit
    @applicant = Applicant.find(params[:id])
  end

  # POST /applicants
  # POST /applicants.json
  def create
    @applicant = Applicant.new(params[:applicant])

    respond_to do |format|
      if @applicant.save
        format.html { redirect_to @applicant, notice: 'Applicant was successfully created.' }
        format.json { render json: @applicant, status: :created, location: @applicant }
      else
        format.html { render action: "new" }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /applicants/1
  # PUT /applicants/1.json
  def update
    @applicant = Applicant.find(params[:id])

    respond_to do |format|
      if @applicant.update_attributes(params[:applicant])
        format.html { redirect_to @applicant, notice: 'Applicant was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @applicant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applicants/1
  # DELETE /applicants/1.json
  def destroy
    @applicant = Applicant.find(params[:id])
    @applicant.destroy

    respond_to do |format|
      format.html { redirect_to applicants_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/views/applicants/_form.html.erb
<%= form_for(@applicant) do |f| %>
  <% if @applicant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@applicant.errors.count, "error") %> prohibited this applicant from being saved:</h2>

      <ul>
      <% @applicant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applicants/edit.html.erb
<h1>Editing applicant</h1>

<%= render 'form' %>

<%= link_to 'Show', @applicant %> |
<%= link_to 'Back', applicants_path %>

app/views/applicants/index.html.erb
<h1>Listing applicants</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @applicants.each do |applicant| %>
  <tr>
    <td><%= applicant.name %></td>
    <td><%= applicant.email %></td>
    <td><%= link_to 'Show', applicant %></td>
    <td><%= link_to 'Edit', edit_applicant_path(applicant) %></td>
    <td><%= link_to 'Destroy', applicant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Applicant', new_applicant_path %>

app/views/applicants/new.html.erb
<h1>New applicant</h1>

<%= render 'form' %>

<%= link_to 'Back', applicants_path %>

app/views/applicants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @applicant.name %>
</p>

<p>
  <b>Email:</b>
  <%= @applicant.email %>
</p>




<table>
  <tr>
    <th>Cv</th>
    <th>Linkedin</th>
    <th>Priority</th>
    <th>Military status</th>
    <th>Application status</th>
    <th>Applicant</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @applicant.applications.each do |application| %>
  <tr>
    <td><%= application.cv %></td>
    <td><%= application.linkedin %></td>
    <td><%= application.priority %></td>
    <td><%= application.military_status %></td>
    <td><%= application.application_status %></td>
    <td><%= application.applicant.name %></td>
    <td><%= link_to 'Show', application %></td>
    <td><%= link_to 'Edit', edit_application_path(application) %></td>
    <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>



<%= link_to 'Edit', edit_applicant_path(@applicant) %> |
<%= link_to 'Back', applicants_path %>