config/routes.rb
JobApplicationApp::Application.routes.draw do
  
  resources :vacant_jobs

  get "sessions/new"

  resources :interviews

  resources :applications

  resources :applicants

  resources :interviewers

  resources :sessions, :only => [:new, :create, :destroy]

  match '/signup', :to => 'interviewers#new'
  match '/signin', :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

end

app/models/interviewer.rb
class Interviewer < ActiveRecord::Base
	has_many :applications

	email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	attr_accessible :name, :position, :email, :password, :password_confirmation
  
  has_secure_password

	  validates :name,	:presence => true,
					:length => { :maximum => 50 }
          
    before_save :encrypt_password

	  validates :password,	:presence => true,
	  						:confirmation => true,
	  						:length => { :within => 6..40 }

	  validates :email, :presence => true,
					:format => { :with => email_regex },
					:uniqueness => true


    def has_password?(submitted_password)
      encrypted_password == encrypt(submitted_password)
    end
    private
      def encrypt_password
        self.salt = make_salt if new_record?
        self.encrypted_password = encrypt(password)
      end
      def encrypt(string)
        secure_hash("#{salt}--#{string}")
      end
      def make_salt
        secure_hash("#{Time.now.utc}--#{password}")
      end
      def secure_hash(string)
        Digest::SHA2.hexdigest(string)
      end
    

end

app/controllers/interviewers_controller.rb
class InterviewersController < ApplicationController
  # GET /interviewers
  # GET /interviewers.json
  def index
    @interviewers = Interviewer.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @interviewers }
    end
  end

  # GET /interviewers/1
  # GET /interviewers/1.json
  def show
    @interviewer = Interviewer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @interviewer }
    end
  end

  # GET /interviewers/new
  # GET /interviewers/new.json
  def new
    @interviewer = Interviewer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @interviewer }
    end
  end

  # GET /interviewers/1/edit
  def edit
    @interviewer = Interviewer.find(params[:id])
  end

  # POST /interviewers
  # POST /interviewers.json
  def create
    @interviewer = Interviewer.new(params[:interviewer])

    respond_to do |format|
      if @interviewer.save
        format.html { redirect_to @interviewer, notice: 'Interviewer was successfully created.' }
        format.json { render json: @interviewer, status: :created, location: @interviewer }
      else
        format.html { render action: "new" }
        format.json { render json: @interviewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /interviewers/1
  # PUT /interviewers/1.json
  def update
    @interviewer = Interviewer.find(params[:id])

    respond_to do |format|
      if @interviewer.update_attributes(params[:interviewer])
        format.html { redirect_to @interviewer, notice: 'Interviewer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @interviewer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /interviewers/1
  # DELETE /interviewers/1.json
  def destroy
    @interviewer = Interviewer.find(params[:id])
    @interviewer.destroy

    respond_to do |format|
      format.html { redirect_to interviewers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/interviewers_helper.rb
module InterviewersHelper
end

app/views/interviewers/_form.html.erb
<%= form_for(@interviewer) do |f| %>
  <% if @interviewer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@interviewer.errors.count, "error") %> prohibited this interviewer from being saved:</h2>

      <ul>
      <% @interviewer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation, "Confirmation" %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/interviewers/edit.html.erb
<h1>Editing interviewer</h1>

<%= render 'form' %>

<%= link_to 'Show', @interviewer %> |
<%= link_to 'Back', interviewers_path %>

app/views/interviewers/index.html.erb
<h1>Listing interviewers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Position</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interviewers.each do |interviewer| %>
  <tr>
    <td><%= interviewer.name %></td>
    <td><%= interviewer.position %></td>
    <td><%= link_to 'Show', interviewer %></td>
    <td><%= link_to 'Edit', edit_interviewer_path(interviewer) %></td>
    <td><%= link_to 'Destroy', interviewer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Sign Up', new_interviewer_path %>

app/views/interviewers/new.html.erb
<h1>New interviewer</h1>

<%= render 'form' %>

<%= link_to 'Back', interviewers_path %>

app/views/interviewers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @interviewer.name %>
</p>

<p>
  <b>Position:</b>
  <%= @interviewer.position %>
</p>



<table>
  <tr>
    <th>Cv</th>
    <th>Linkedin</th>
    <th>Priority</th>
    <th>Military status</th>
    <th>Vacany</th>
    <th>Application status</th>
    <th>Applicant</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @interviewer.applications.each do |application| %>
  <tr>
    <td><%= application.cv %></td>
    <td><%= application.linkedin %></td>
    <td><%= application.priority %></td>
    <td><%= application.military_status %></td>
    <td><%= application.vacany_id %></td>
    <td><%= application.application_status %></td>
    <td><%= application.applicant.name %></td>
    <td><%= link_to 'Show', application %></td>
    <td><%= link_to 'Edit', edit_application_path(application) %></td>
    <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>


<%= link_to 'Edit', edit_interviewer_path(@interviewer) %> |
<%= link_to 'Back', interviewers_path %>